# Generated by Django 5.1.2 on 2024-12-20 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(default='default_node_id', max_length=50)),
                ('position', models.JSONField()),
                ('data', models.JSONField()),
                ('type', models.CharField(max_length=50)),
                ('measured', models.JSONField()),
                ('selected', models.BooleanField(default=False)),
                ('dragging', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='crhg.patient')),
            ],
            options={
                'unique_together': {('patient', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(default='default_edge_id', max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='crhg.patient')),
            ],
            options={
                'unique_together': {('patient', 'edge_id')},
            },
        ),
    ]
