# Generated by Django 5.1.2 on 2024-12-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crhg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='edge_id',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
